<a href="https://colab.research.google.com/github/Shisiajoy/PYTHON-DATA-ANALYSIS/blob/main/pandas16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MPG Cars

Introduction:

The following exercise utilizes data from UC Irvine Machine Learning Repository

Step 1. Import the necessary libraries

In [1]:
import pandas as pd

Step 2. Import the first dataset cars1 and cars2.

Step 3. Assign each to a variable called cars1 and cars2

In [3]:
url1='https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv'
cars1 = pd.read_csv(url1)

url2 = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv'
cars2 = pd.read_csv(url2)

In [4]:
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

In [10]:
cars2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l

Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [9]:
cars1.loc[:, ~cars1.columns.str.contains('^Unnamed')]
cars1.head(20)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster
16,18.0,6,199,97,2774,15.5,70,1,amc hornet
17,21.0,6,200,85,2587,16.0,70,1,ford maverick
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan

Step 5. What is the number of observations in each dataset?

In [11]:
num_observations_cars1 = cars1.shape[0]
num_observations_cars2 = cars2.shape[0]
print("Number of observations in cars1:", num_observations_cars1)
print("Number of observations in cars2:", num_observations_cars2)

Number of observations in cars1: 198
Number of observations in cars2: 200

Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [12]:
cars = pd.concat([cars1, cars2], ignore_index=True)
cars.head(15)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii

Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [13]:
import numpy as np
np.random.seed(0)  # For reproducibility
owners = np.random.randint(15000, 73001, size=cars.shape[0])

In [14]:
print(owners)

[17732 58567 57613 67416 60891 36243 45403 47103 56993 72043 35757 70026
 61884 29935 30430 63600 54512 67620 29650 32089 47230 33983 58095 66374
 39152 50665 31921 42469 53984 21921 53804 17163 20072 52619 22877 33430
 16871 22599 17496 62954 39675 57968 46921 48523 15797 64811 18219 30246
 39999 71608 31321 67489 34129 68887 56504 70839 64866 33676 72495 46230
 26723 58890 32591 70324 58136 41752 38605 21021 35006 18560 40332 46055
 60444 65793 61522 62647 36368 35737 43647 41681 29627 27134 62883 56390
 71402 35571 66811 24781 34340 42257 31298 27372 66403 19420 60830 54876
 32455 29324 53019 22012 24396 62080 18918 24359 65836 59259 38482 30127
 58727 50725 52237 29165 23752 57565 29505 20795 65624 38647 55133 43254
 56216 70153 51530 40392 31221 33819 49402 63682 15973 35848 25215 26157
 39777 28824 17418 27843 28242 51223 70319 69971 21521 37626 71894 24123
 46454 57947 70890 29254 66939 38700 52073 66762 53299 38310 46785 30041
 71356 38306 51950 63171 28160 41635 62874 48075 28392 29368 20302 48920
 38334 56235 53062 61634 61451 65360 50260 42112 63717 62390 28592 40213
 48538 30875 23286 59258 53763 33728 28640 18091 60663 18912 65586 21594
 36752 72524 38532 22997 68006 55800 30620 55899 19845 41763 69268 58606
 18533 17937 41221 52707 57512 34608 20021 41773 48902 64177 57448 32340
 16913 67086 28429 28907 50489 25088 65080 30588 53395 70417 53214 15469
 58295 23717 66015 49488 53040 31975 53953 66474 30912 43086 31591 30115
 68414 29447 67573 43665 69401 57870 26052 72560 30741 72368 43739 58986
 20103 72091 50050 16740 70270 27579 20846 61078 62805 35165 17775 33987
 45752 38563 28928 21356 48930 61774 43651 30997 48391 47232 23962 35435
 49009 58671 19403 32582 44844 34381 53429 30939 25787 32191 17121 60353
 39451 18886 56690 37450 30212 24987 65975 62881 60485 31583 49215 20181
 58349 26042 57914 20208 21177 62749 19863 70332 65944 65635 62394 23389
 15894 69526 63208 45142 47904 41813 54041 40968 62395 28688 18419 31552
 21004 50620 60232 57521 35803 72191 72852 30139 50954 37302 36533 33161
 67513 56106 69545 68469 29676 35989 17562 37597 40484 52420 28173 42389
 61402 43271 70387 26605 48191 43310 71006 48735 52138 56820 37571 69355
 48201 28097 37621 32813 59889 33930 46200 29299 31713 34996 31363 39785
 70913 51736 39534 47319 16040 21250 72508 40182 22704 21772 53079 57179
 40907 60192 24144 42741 53779 66950 56120 17195 19680 70751 40687 67237
 47058 69865]

Step 8. Add the column owners to cars

In [15]:
cars['owners'] = owners

# Display the updated DataFrame
print("\nCars DataFrame with 'owners' column:")
print(cars.head())

Cars DataFrame with 'owners' column:
    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70
1  15.0          8           350        165    3693          11.5     70
2  18.0          8           318        150    3436          11.0     70
3  16.0          8           304        150    3433          12.0     70
4  17.0          8           302        140    3449          10.5     70

   origin                        car  owners
0       1  chevrolet chevelle malibu   17732
1       1          buick skylark 320   58567
2       1         plymouth satellite   57613
3       1              amc rebel sst   67416
4       1                ford torino   60891